export const EN = {
  EMAIL_ADDRESS: "Email Address",
  PASSWORD: "Password",
  LOGIN: "Log in",
  WELCOME_BACK_HEADING: "Hi ! Welcome back.",
  WELCOME_SUB_HEADING: "Use your shared credentials to log in",
  NEED_HELP: "Need help?",
  LOGIN_INFO_HEADING: "Welcome to Nerito!",
  NERITO_DESC:
    "Nerito is the wallet app that allows you to make transfers, receive cash payments, allows you to manage your payroll",
  LOGIN_HELPER_TEXT: "Please enter correct login ID and password",
  LOGIN_INFO_1: "The site that allows you to manage payroll",
  USER_QUESTION: "Still not a user of our platform?",
  CONTACT_US: "Contacta con nosotros",
  COMPANY_NAME: "Company",
  EMPLOYEE_FILE_UPLOAD_DATE: "Employee File Upload Date",
  EMPLOYEE_FILE_VERIFICATION_DATE: "Employee File Verification Date",
  PAYROLL_FILE_UPLOAD_DATE: "Payroll File Upload Date",
  PAYROLL_FILE_VERIFICATION_DATE: "Payroll File Verification Date",
  PAYROLL_DISBURSEMENT_DATE: "Payroll Disbursement Date",
  SUBMIT: "Submit",
  UPDATE: "Update",
  CANCEL: "Cancel",
  PLEASE_FILL: "Please fill",
  EMP_ENROLLMENT_DATE: "Employee Enrollment Date",
  STATUS: "Status",
  ACTION: "Action",
  ACTIVATED: "Activate",
  DEACTIVATED: "Deactivate",
  EDIT: "Edit",
  ATTACH_FILE: "Attach file",
  SEARCH_EMPLOYEES: "Search Employees",
  COMPANY_INFORMATION: "Company Information",
  LIST_COMPANIES: "List of companies",
  REGISTER_NEW_COMPANY: "Register new company",
  COMPANY_DETAILS: "Details",
  FISCAL_INFO: "Fiscal Info",
  PAYROLL_USERS: "Payroll Users",
  ACCOUNT_USERS: "Account Users",
  PAYROLL_DISBURSEMENT: "Disbursement Date",
  ENROLLMENT_DATE: "Enrollment date",
  EMAIL: "Email",
  OK: "OK",
  FORM_SUBMITTED_SUCCESSFULLY: "Form submitted successfully!",
  FORM_DELETED_SUCCESSFULLY: "Form deleted successfully!",
  DELETE_COMPANY_CONFIRMATION:
    "Are you sure you want to delete this company entry?",
  SEARCH_KEYWORD: "Search Keyword",
  HOME: "Home",
  LOGOUT: "Logout",
  PAYROLL_DISBURSEMENT_APP: "Payroll Disbursement App",
  PLEASE_SELECT: "Please Select",
  API_ERROR_MESSAGE: "Oops! Something went wrong.",
  COMPANY_CREATED_SUCCESSFULLY: "Company Created Successfully.",
  COMPANY_UPDATED_SUCCESSFULLY: "Company Updated Successfully.",
  COMPANY_DELETED_SUCCESSFULLY: "Company Deleted Successfully.",
  EMPLOYEE_CREATED_SUCCESSFULLY: "Employee Created Successfully.",
  EMPLOYEE_UPDATED_SUCCESSFULLY: "Employee Updated Successfully.",
  EMPLOYEE_DELETED_SUCCESSFULLY: "Employee Deleted Successfully.",
  EMPLOYEE_LIST_FREEZE: "Employee list freeze for current month",
  EMPLOYEE_LIST_UNFREEZE: "Employee list unfreeze for current month",
  PLEASE_FILL_REQUIRED_FIELD: "This field is required.",
  EMAIL_NOT_VALID: "Email is not valid.",
  ENTER_COMPANY_NAME: "Enter Company Name",
  ENTER_FISCAL_INFORMATION: "Enter Fiscal Information",
  ENTER_EMAIL_ADDRESS: "Enter Email Address",
  PLEASE_ENTER_COMPANY_DETAILS: "Please Enter Company Details",
  MANAGMENT_PAYROLL: "Management of Payroll Users",
  EMPLOYEE_LIST: "Employee List",
  UPLOAD_EMPLOYEE_DETAILS: "Upload CSV",
  INSTRUCTION_LOADING_DATA_ACCOUNT_USER:
    "Instructions for loading Account Users data",
  INSTRUCTION_LOADING_DATA_PAYROLL_USER:
    "Instructions for loading Payroll Users data",
  DOWNLOAD_FORMAT: "DOWNLOAD FORMAT",
  RFC_EMPLOYEE: "RFC Employee",
  LAST_NAME: "Last Name",
  MOTHERS_LAST_NAME: "Mother's last name",
  SALARY_RANGE: "Salary range",
  VIEW_INFORMATION_BY: "View information by",
  NAME: "Name",
  MONTH: "Month",
  YEAR: "Year",
  SEND: "Send",
  VALIDATE_PAYROLL_RECORD: "Validate Payroll Record",
  OF_THE_MONTH: "of the month",
  DATE_OF_BIRTH: "Date of Birth",
  GENDER: "Gender",
  MALE: "Male",
  FEMALE: "Female",
  ADDRESS: "Address",
  PHONE_NUMBER: "Phone Number",
  VIEW: "View",
  ENTER_PASSWORD_HERE: "Enter password here",
  ENTER_EMAIL_HERE: "Enter email here",
  JANUARY: "January",
  FEBRUARY: "February",
  MARCH: "March",
  APRIL: "April",
  MAY: "May",
  JUNE: "June",
  JULY: "July",
  AUGUST: "August",
  SEPTEMBER: "September",
  OCTOBER: "October",
  NOVEMBER: "November",
  DECEMBER: "December",
  PLEASE_ENTER_COMPNAY_DETAILS: "Please Enter Company Details",
  EXAMINE: "Examine",
  UPLOAD_YOUR_FILE: "Upload Your File",
  CSV_VALIDATION: {
    INVALID_HEADER: "Invalid Header",
    MINIMUM_ROW_VALIDATION: "Fill at least 1 row in CSV to upload",
    VALIDATE_ROW_EMPTY: "Some column in rows are empty",
    VALIDATE_EMAIL_PHONENUMBER: "Email or Phone Number is not valid",
  },
  DRAG_DROP: "Drag and drop your files here",
  CLICK_TO_UPLOAD: "Click here to select the file",
  OR: "OR",
  STEP01: "Step 01",
  STEP02: "Step 02",
  STEP03: "Step 03",
  STEP04: "Step 04",
  YOU_CAN_ATTACH_A_CSV_FILE_YOUR_COMPUTER:
    "Puedes adjuntar un archivo .CSV desde tu equipo:",
  DOWNLOAD_THE_FORM_AND_FILL_IT_IN_WITH_YOUR_COMPANY_DATA:
    "Download the form and fill it in with your company data.",
  PRESS_THE_BROWSE_BUTTON_TO_IMPORT_THE_FILE_FROM_YOUR_COMPUTER:
    "Press the Browse button to import the file from your computer.",
  CHANGE_THE_NAME_IF_YOU_WANT: "Change the name if you want.",
  PRESS_ATTACH_FILE_TO_CONTINUE: "Press attach file to continue.",
  PLEASE_SELECT_THE_FILE: "Please select the file..",
  EMPLOYEE_INFORMATION: "Employee Information",
  RFC: "RFC",
  FIRST_NAME: "First Name",
  CITY: "City",
  STATE: "State",
  ADDRESSES: "Addresses",
  DELETE_EMPLOYEE_CONFIRMATION: "Confirm employee deletion?",
  FREEZE_EMPLOYEE_CONFIRMATION:
    "Are you sure to freeze the employee for this month?",
  TYPE_ACCOUNT: "Account Type",
  BANK_ID: "Bank Id",
  ACCOUNT_CLABE: "Account Clabe",
  VIEW_ERROR: "View Error",
  FREEZE: "Freeze",
  THEME_COLOR: "Theme Colors",
  FILE_INPUT_VALIDATION: "File FIeld Validation",
  LOGO: "Logo",
  PRIMARY_COLOR: "Primary Color",
  SECONDARY_COLOR: "Secondary Color",
  ERROR_COLOR: "Error Color",
  SUCCESS_COLOR: "Success Color",
  CONTACT: "Contact",
  COMPANY_ID: "Company Id",
  OPERATION_TYPE: "Operation Type",
  CURRENCY: "Currency",
  TRANSFER_TO: "Transfer to",
  ERROR_NO_COMPANY_ASSIGNED: "There is no company assigned.",
  COMPANY_CAN_NOT_CREATED:
    "Company Can not create. Account user or Payroll User is not exist.",
  INVALID: "Invalid",
  SHOULD_BE_UNIQUE: "should be unique",
  IS_A_MANDATORY_FIELD: "is a mandatory field",
  ACCOUNT_CLABE_CAN_NOT_BE_MORE_THAN_18_CHARACTERS:
    "can not be more than 18 characters",
  RFC_CAN_NOT_BE_MORE_THAN_13_CHARACTERS: "can not be more than 13 characters",
  CONTACT_CAN_NOT_BE_MORE_THAN_20_CHARACTERS:
    "can not be more than 20 characters",
  LOGO_SHOULD_BE_SMALLER_THAN_1_MB: "Logo should be smaller than 1 MB.",
  COMPANY_LOGO: "Company Logo",
  MANAGMENT_ACCOUNT: "Management of Account Users",
  OPERATION: "Operation",
  ORIGIN_ACCOUNT: "Origin Account",
  DESTINATION_ACCOUNT: "Destination Account",
  IMPORT_AMOUNT: "Import (Amonut)",
  REFERENCE: "Reference",
  DESCRIPTION: "Description",
  ORIGIN_CURRENCY: "Origin Currency",
  DESTINATION_CURRENCY: "Destination Currency",
  ORDENING_PAYER_RFC: "RFC Payer",
  IVA: "IVA",
  BENEFICIARY_EMAIL: "Beneficiary e-mail",
  APPLICATION_DATE: "Application Date",
  PAYMENT_INSTRUCTIONS: "Payment instructions",
  SALARY_EMPLOYEE_LIST_FREEZE: "Salary employee list freeze for current month",
  SALARY_EMPLOYEE_LIST_UNFREEZE:
    "Salary employee list unfreeze for current month",
  SALARY_EMPLOYEE_CREATED_SUCCESSFULLY: "Salary employee Created Successfully.",
  SALARY_EMPLOYEE_UPDATED_SUCCESSFULLY: "Salary employee Updated Successfully.",
  SALARY_EMPLOYEE_DELETED_SUCCESSFULLY: "Salary employee Updated Successfully.",
  UPLOAD_SALARY_EMPLOYEE_DETAILS: "Upload employee's salary details",
  SALARY_EMPLOYEE_LIST: "Salary employee list",
  USER_NAME: "User Name",
  TYPE_OF_OPERATION: "Type of operation",
  BANK: "Bank",
  BADGES: "Badges",
  SUPER_ADMIN: "Super Admin",
  UNFREEZE: "Unfreeze",
  ENTER_YOUR_NAME: "Enter Your Name Here",
  FIELD_UNIQUE: "Field must be unique",
  SOMETHING_WENT_WRONG: "Something went wrong",
  MAX_CHARACTER_LENGTH_RFC: "Maximum character length is 13",
  MAX_CHARACTER_LENGTH_EMAIL: "Maximum character length is 39",
  PHONE_NUMBER_NOT_VALID: "Phone number is not valid",
  SUCCESS_BTN: "Success",
  FAILURE_BTN: "Faliure",
  SUCCESS: "Registrations processed successfully",
  FAILURE: "Records with errors",
  NO_RECORD_FOUND: "No record found",
  MANAGMENT_PAYROLL_OPEARATION: "Payroll Management-Employee Account",
  MANAGMENT_ACCOUNT_OPEARATION: "Payroll Management-Payroll Dispersion",
  BANK_RESPONSE: "Bank Response",
  EXECUTION_DATE: "Execution Date",
  TRACKING_ID: "TrackingID",
  MOVEMENT_NUMBER: "Movement Number",
  ACCOUNT_HOLDER: "Account Holder",
  SUCCESS_MSG: "Success Msg",
  ERROR_MSG: "Error Msg",
};
