export const ES = {
  EMAIL_ADDRESS: "Dirección de correo electrónico",
  PASSWORD: "Contraseña",
  LOGIN: "Iniciar Sesión",
  WELCOME_BACK_HEADING: "Hola ! Bienvenido de nuevo.",
  WELCOME_SUB_HEADING:
    "Utilice sus credenciales compartidas para iniciar sesión",
  NEED_HELP: "¿Necesitas ayuda?",
  LOGIN_INFO_HEADING: "¡Bienvenido a Nerito!",
  NERITO_DESC:
    "Nerito es la app de wallet que te permite realizar transferencias, recibir pagos en efectivo, te permite administrar tu nómina",
  LOGIN_INFO_1: "El sitio que te permite adiministrar el pago de nóminas",
  LOGIN_HELPER_TEXT:
    "Ingrese el ID de inicio de sesión y la contraseña correctos",
  USER_QUESTION: "¿Aún no eres usuario de nuestra plataforma?",
  CONTACT_US: "Contacta con nosotros",
  COMPANY_NAME: "Nombre empresa",
  EMPLOYEE_FILE_UPLOAD_DATE: "Fecha de carga del archivo del empleado",
  EMPLOYEE_FILE_VERIFICATION_DATE:
    "Fecha de verificación del archivo del empleado",
  PAYROLL_FILE_UPLOAD_DATE: "Fecha de carga del archivo de nómina",
  PAYROLL_FILE_VERIFICATION_DATE: "Fecha de verificación del archivo de nómina",
  PAYROLL_DISBURSEMENT_DATE: "Fecha de desembolso de la nómina",
  SUBMIT: "GUARDAR",
  UPDATE: "GUARDAR",
  CANCEL: "Cancelar",
  PLEASE_FILL: "Porfavor llene",
  EMP_ENROLLMENT_DATE: "Emp Fecha de inscripción",
  STATUS: "Estado",
  ACTION: "Acción",
  ACTIVATED: "Activado",
  DEACTIVATED: "Desactivado",
  EDIT: "Editar",
  ATTACH_FILE: "Adjuntar archivo",
  SEARCH_EMPLOYEES: "Buscar empleados",
  COMPANY_INFORMATION: "Información de la empresa",
  LIST_COMPANIES: "Listado de empresas",
  REGISTER_NEW_COMPANY: "Inscribir nueva empresa",
  COMPANY_DETAILS: "Detalles",
  FISCAL_INFO: "Información fiscal",
  PAYROLL_USERS: "Usuario de dispersion",
  ACCOUNT_USERS: "Usuarios cuenta",
  PAYROLL_DISBURSEMENT: "Fecha de desembolso",
  ENROLLMENT_DATE: "Fecha de inscripción",
  EMAIL: "Correo electrónico",
  OK: "OK",
  FORM_SUBMITTED_SUCCESSFULLY: "Formulario enviado con éxito",
  FORM_DELETED_SUCCESSFULLY: "Formulario eliminado correctamente",
  DELETE_COMPANY_CONFIRMATION:
    "¿Está seguro de que desea eliminar esta entrada de empresa",
  SEARCH_KEYWORD: "Buscar la palabra clave",
  HOME: "Inicio",
  LOGOUT: "Cerrar sesión",
  PAYROLL_DISBURSEMENT_APP: "Aplicación de desembolso de nómina",
  PLEASE_SELECT: "Por favor seleccione",
  API_ERROR_MESSAGE: "¡UPS Algo salió mal.",
  COMPANY_CREATED_SUCCESSFULLY: "Empresa creada con éxito.",
  COMPANY_UPDATED_SUCCESSFULLY: "Empresa actualizada correctamente.",
  COMPANY_DELETED_SUCCESSFULLY: "Empresa eliminada con éxito.",
  EMPLOYEE_CREATED_SUCCESSFULLY: "Empleado creado con éxito.",
  EMPLOYEE_UPDATED_SUCCESSFULLY: "Empleado actualizado con éxito.",
  EMPLOYEE_DELETED_SUCCESSFULLY: "Empleado eliminado con éxito.",
  EMPLOYEE_LIST_FREEZE:
    "Congelación de la lista de empleados para el mes actual",
  EMPLOYEE_LIST_UNFREEZE: "Lista de empleados descongelada para el mes actual",
  PLEASE_FILL_REQUIRED_FIELD: "Este campo es requerido.",
  EMAIL_NOT_VALID: "El correo no es válido.",
  ENTER_COMPANY_NAME: "Ingrese el nombre de la empresa",
  ENTER_FISCAL_INFORMATION: "Ingrese información fiscal",
  ENTER_EMAIL_ADDRESS: "Introduzca la dirección de correo electrónico",
  PLEASE_ENTER_COMPANY_DETAILS: "Ingrese los detalles de la empresa",
  MANAGMENT_PAYROLL: "Gestión de usuarios de nómina",
  EMPLOYEE_LIST: "Lista de empleados",
  UPLOAD_EMPLOYEE_DETAILS: "Cargar datos",
  INSTRUCTION_LOADING_DATA_ACCOUNT_USER:
    "Instrucciones para carga de datos al sistema",
  INSTRUCTION_LOADING_DATA_PAYROLL_USER:
    "Instrucciones para carga de datos al sistema",
  DOWNLOAD_FORMAT: "DESCARGAR FORMATO",
  RFC_EMPLOYEE: "RFC Empleado",
  LAST_NAME: "Apellido paterno",
  MOTHERS_LAST_NAME: "Apellido materno",
  SALARY_RANGE: "Rango sueldo",
  VIEW_INFORMATION_BY: "Ver información por",
  NAME: "Nombre y Apellido",
  MONTH: "Mes",
  YEAR: "Año",
  SEND: "Enviar",
  VALIDATE_PAYROLL_RECORD: "Validar registro de nómina",
  OF_THE_MONTH: "del mes",
  DATE_OF_BIRTH: "Fecha de cumpleaños",
  GENDER: "Género",
  MALE: "Masculino",
  FEMALE: "Femenino",
  ADDRESS: "Dirección",
  PHONE_NUMBER: "Número de teléfono",
  VIEW: "FILTRAR",
  ENTER_PASSWORD_HERE: "Ingreso contraseña",
  ENTER_EMAIL_HERE: "Ingrese correo electrónico",
  JANUARY: "Enero",
  FEBRUARY: "Febrero",
  MARCH: "Marzo",
  APRIL: "Abril",
  MAY: "Mayo",
  JUNE: "Junio",
  JULY: "Julio",
  AUGUST: "Agosto",
  SEPTEMBER: "Septiembre",
  OCTOBER: "Octubre",
  NOVEMBER: "Noviembre",
  DECEMBER: "Diciembre",
  PLEASE_ENTER_COMPNAY_DETAILS: "Introduzca los datos de la empresa.",
  EXAMINE: "Validar archivo",
  OR: "O",
  UPLOAD_YOUR_FILE: "Sube tu archivo",
  CSV_VALIDATION: {
    INVALID_HEADER: "Encabezado no válido",
    MINIMUM_ROW_VALIDATION: "Complete al menos 1 fila en CSV para cargar",
    VALIDATE_ROW_EMPTY: "Algunas columnas de las filas están vacías",
    VALIDATE_EMAIL_PHONENUMBER:
      "El correo electrónico o el número de teléfono no son válidos",
  },
  DRAG_DROP: "Arrastre y suelte sus archivos aquí",
  CLICK_TO_UPLOAD: "Haga clic aquí para seleccionar el archivo",
  STEP01: "Paso 01",
  STEP02: "Paso 02",
  STEP03: "Paso 03",
  STEP04: "Paso 04",
  YOU_CAN_ATTACH_A_CSV_FILE_YOUR_COMPUTER:
    "Puedes adjuntar un archivo .CSV desde tu equipo:",
  DOWNLOAD_THE_FORM_AND_FILL_IT_IN_WITH_YOUR_COMPANY_DATA:
    "Descarga el formulario y rellénalo con los datos de tu empresa.",
  PRESS_THE_BROWSE_BUTTON_TO_IMPORT_THE_FILE_FROM_YOUR_COMPUTER:
    "Presione el botón Examinar para importar el archivo desde su computadora.",
  CHANGE_THE_NAME_IF_YOU_WANT: "Cambie el nombre si lo desea.",
  PRESS_ATTACH_FILE_TO_CONTINUE: "Presione adjuntar archivo para continuar.",
  PLEASE_SELECT_THE_FILE: "Seleccione el archivo ..",
  EMPLOYEE_INFORMATION: "Información del empleado",
  RFC: "RFC",
  FIRST_NAME: "Primer nombre",
  CITY: "Ciudad",
  STATE: "Estado",
  ADDRESSES: "Direcciones",
  DELETE_EMPLOYEE_CONFIRMATION: "¿Confirma eliminación del empleado?",
  FREEZE_EMPLOYEE_CONFIRMATION:
    "¿Está seguro de confirmar la información de empleados para el período?",
  TYPE_ACCOUNT: "Tipo de cuenta",
  BANK_ID: "ID del banco",
  ACCOUNT_CLABE: "Nro. Cuenta/CLABE",
  VIEW_ERROR: "Ver error",
  FREEZE: "Congelar",
  THEME_COLOR: "Temas Colores",
  FILE_INPUT_VALIDATION: "Validación de campo de archivo",
  LOGO: "Logo",
  PRIMARY_COLOR: "Color primario",
  SECONDARY_COLOR: "Color secundario",
  ERROR_COLOR: "Color de error",
  SUCCESS_COLOR: "Color de éxito",
  CONTACT: "Contacto",
  COMPANY_ID: "ID de la compañía",
  OPERATION_TYPE: "Tipo de operación",
  CURRENCY: "Divisa",
  TRANSFER_TO: "Transferir a",
  ERROR_NO_COMPANY_ASSIGNED: "No hay empresa asignada.",
  ACCOUNT_USER: "Usuarios cuenta",
  COMPANY_CAN_NOT_CREATED:
    "Empresa No se puede crear. El usuario de la cuenta o el usuario de la nómina no existe.",
  INVALID: "Inválido",
  SHOULD_BE_UNIQUE: "Debe ser único",
  IS_A_MANDATORY_FIELD: "es un campo obligatorio",
  ACCOUNT_CLABE_CAN_NOT_BE_MORE_THAN_18_CHARACTERS:
    "no puede tener más de 18 caracteres",
  RFC_CAN_NOT_BE_MORE_THAN_13_CHARACTERS: "no puede tener más de 13 caracteres",
  CONTACT_CAN_NOT_BE_MORE_THAN_20_CHARACTERS:
    "no puede tener más de 20 caracteres",
  LOGO_SHOULD_BE_SMALLER_THAN_1_MB:
    "El logotipo debe tener un tamaño inferior a 1 MB.",
  COMPANY_LOGO: "Logo de la compañía",
  MANAGMENT_ACCOUNT: "Gestión de Cuentas de Usuarios",
  OPERATION: "Operación",
  ORIGIN_ACCOUNT: "Cuenta de origen",
  DESTINATION_ACCOUNT: "cuenta de destino",
  IMPORT_AMOUNT: "Importe (Cantidad)",
  REFERENCE: "Referencia",
  DESCRIPTION: "Descripción",
  ORIGIN_CURRENCY: "Moneda de origen",
  DESTINATION_CURRENCY: "Moneda de destino",
  ORDENING_PAYER_RFC: "RFC Pagador",
  IVA: "IVA",
  BENEFICIARY_EMAIL: "Correo electrónico del beneficiario",
  APPLICATION_DATE: "Fecha de aplicacion",
  PAYMENT_INSTRUCTIONS: "Instrucciones de pago",
  SALARY_EMPLOYEE_LIST_FREEZE:
    "Congelación de lista de empleados a sueldo para el mes en curso",
  SALARY_EMPLOYEE_LIST_UNFREEZE:
    "Descongelación de la lista de empleados de salario para el mes actual",
  SALARY_EMPLOYEE_CREATED_SUCCESSFULLY: "Empleado salarial creado con éxito.",
  SALARY_EMPLOYEE_UPDATED_SUCCESSFULLY:
    "Empleado salarial Actualizado con éxito.",
  SALARY_EMPLOYEE_DELETED_SUCCESSFULLY:
    "Empleado salarial eliminado con éxito.",
  UPLOAD_SALARY_EMPLOYEE_DETAILS: "Cargar datos",
  SALARY_EMPLOYEE_LIST: "Lista de asalariados",
  USER_NAME: "Nombre de usuario",
  TYPE_OF_OPERATION: "Tipo de operación",
  BANK: "Banco",
  BADGES: "Insignias",
  SUPER_ADMIN: "SÚPER ADMINISTRADOR",
  UNFREEZE: "Descongelar",
  ENTER_YOUR_NAME: "Introduzca su nombre aquí",
  FIELD_UNIQUE: "El campo debe ser único",
  SOMETHING_WENT_WRONG: "Algo salió mal",
  MAX_CHARACTER_LENGTH_RFC: "La longitud máxima de caracteres es 13",
  MAX_CHARACTER_LENGTH_EMAIL: "La longitud máxima de caracteres es 39",
  PHONE_NUMBER_NOT_VALID: "El número de teléfono no es válido",
  SUCCESS_BTN: "EXITO",
  FAILURE_BTN: "ERRORES",
  SUCCESS: "Registros procesados con éxito",
  FAILURE: "Registros con errores",
  NO_RECORD_FOUND: "No se encontraron datos",
  MANAGMENT_PAYROLL_OPEARATION: "Gestión de Nóminas-Dispersión de Nóminas",
  MANAGMENT_ACCOUNT_OPEARATION: "Gestión de Nóminas-Cuenta de Empleados",
  BANK_RESPONSE: "Respuesta del banco",
  EXECUTION_DATE: "Fecha de ejecución",
  TRACKING_ID: "ID de rastreo",
  MOVEMENT_NUMBER: "Número de movimiento",
  ACCOUNT_HOLDER: "Titular de la cuenta",
  SUCCESS_MSG: "Registros procesados con éxito",
  ERROR_MSG: "Registros procesados con error",
};
